### ISSUE TITLE
KeyError: 'Transcript ID'

### ISSUE THREAD

**Issue by marissaDubbelaar** [nf-core/epitopeprediction#146]
### Description of the bug

The run breaks in the `NFCORE_EPITOPEPREDICTION:EPITOPEPREDICTION:PEPTIDE_PREDICTION_VAR` step since there is an "Transcript ID" in the file

### Command used and terminal output

```console
NXF_VERSION=21.10.4 nextflow run nf-core/epitopeprediction \
-r dev \
--input "" \
--outdir '' \
--genome_version "GRCh38" \
-profile cfc \
-resume
```

```
nf-core/epitopeprediction execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:
Error executing process > 'NFCORE_EPITOPEPREDICTION:EPITOPEPREDICTION:PEPTIDE_PREDICTION_VAR (7)'

Caused by:
  Process `NFCORE_EPITOPEPREDICTION:EPITOPEPREDICTION:PEPTIDE_PREDICTION_VAR (7)` terminated with an error exit status (1)

Command executed:
  epaa.py --identifier Strelka_QATLV065AG_variants_snpEff.ann.chr15         --alleles 'A*02:01;A*68:01;B*27:05;B*51:01;C*01:02;C*14:02'         --versions versions.csv         --tools syfpeithi --mhcclass 1 --max_length 11 --min_length 8 --reference GRCh38 --somatic_mutation Strelka_QATLV065AG_variants_snpEff.ann.chr15.vcf
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_EPITOPEPREDICTION:EPITOPEPREDICTION:PEPTIDE_PREDICTION_VAR":
      python: $(python --version 2>&1 | sed 's/Python //g')
      fred2: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('Fred2').version)")
      pandas: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('pandas').version)")
      pyvcf: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('pyvcf').version)")
      mhcflurry: $(mhcflurry-predict --version 2>&1 | sed 's/^mhcflurry //; s/ .*$//')
      mhcnuggets: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('mhcnuggets').version)")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Using TensorFlow backend.
  Traceback (most recent call last):
    File "/home-link/kmhmd01/.nextflow/assets/nf-core/epitopeprediction/bin/epaa.py", line 1168, in 
      __main__()
    File "/home-link/kmhmd01/.nextflow/assets/nf-core/epitopeprediction/bin/epaa.py", line 1000, in __main__
      transcriptProteinMap, transcriptSwissProtMap = get_protein_ids_for_transcripts(ID_SYSTEM_USED, transcripts, references[args.reference], args.reference)
    File "/home-link/kmhmd01/.nextflow/assets/nf-core/epitopeprediction/bin/epaa.py", line 671, in get_protein_ids_for_transcripts
      if dic[key] in result:
  KeyError: 'Transcript ID'

Work dir:
  /sfs/7/workspace/ws/kmhmd01-QATLV_Walz-0/Pipeline_running/work/df/cb4513643469930d1136cbfcc90bd8
```
```


### Relevant files

[nextflow.log](https://github.com/nf-core/epitopeprediction/files/8222578/nextflow.log)


### System information

- Nextflow version: 21.10.4
- Hardware: HPC
- Executor: slurm
- Version of nf-core/epitopeprediction: dev

**Comment by christopher-mohr** [comment]
Could not reproduce it so far. Waiting for feedback.

**Comment by marissaDubbelaar** [comment]
Yea I looked into it again, but I also cannot reproduce it anymore. Tried the run again but the run takes a long time in the `PEPTIDE_PREDICTION_VAR` and then ends after a day or so with a lot of messages. Each time the error is different
